CREATE DATABASE IF NOT EXISTS FUNDAPEC_DB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE FUNDAPEC_DB;

-- Tabla ESTUDIANTE
CREATE TABLE IF NOT EXISTS ESTUDIANTE (
    MATRICULA VARCHAR(20) NOT NULL,
    ESTADO VARCHAR(30) NOT NULL,
    PERIODO_ACADEMICO VARCHAR(20) NOT NULL,
    DESCRIPCION_PERIODO VARCHAR(60),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MATRICULA)
) ENGINE = InnoDB;

-- Tabla DETALLE_PAGO
CREATE TABLE IF NOT EXISTS DETALLE_PAGO (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CODIGO_PAGO VARCHAR(50) NOT NULL,
    MONTO_APROBADO DECIMAL(15,2) NOT NULL,
    MONEDA VARCHAR(5) NOT NULL,
    FECHA_APROBACION DATE NOT NULL,
    MATRICULA VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_CODIGO_PAGO (CODIGO_PAGO),
    INDEX IDX_MATRICULA (MATRICULA),
    CONSTRAINT FK_DETALLE_ESTUDIANTE FOREIGN KEY (MATRICULA)
    REFERENCES ESTUDIANTE (MATRICULA)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB;

INSERT INTO ESTUDIANTE (MATRICULA, ESTADO, PERIODO_ACADEMICO, DESCRIPCION_PERIODO)
VALUES ('A00000001','Activo','2026-C1','Ene-Abr 2026');

INSERT INTO DETALLE_PAGO (CODIGO_PAGO, MONTO_APROBADO, MONEDA, FECHA_APROBACION, MATRICULA)
VALUES ('FUNDAPEC-CR-000001', 53006.80, 'DOP', '2026-01-28', 'A00000001');
